### PR TITLE
If no types, remove the empty dropdown

### PR DESCRIPTION
**Pull request by wilr**

### CODE REVIEW

**Comment by emteknetnz** [comment]
I'm not sure about this one, I think the user experience is better showing the dropdown with no option as it communications to the cms-user that there is this 'Types' functionality at least available, even if it's unused.

@clarkepaul what's your take on this one from a UX perspective?

**Default when no Taxonomy Types are available:**

image

**Pull-request:**

image

@wilr if we do go with this one, there were a couple of PHPCS things that needed tidying up https://travis-ci.com/github/silverstripe/silverstripe-taxonomy/jobs/453139595

**Comment by wilr** [comment]
@emteknetnz In this particular project we've hidden the Types tab completely now to prevent CMS editors from asking about it. I've just done it project specific in CSS but if potentially could take it one step further and have a config() option to disable types

**Comment by emteknetnz** [comment]
Good idea @wilr

How do you go about removing the TaxonomyType tab in your project?  It seems like the correct way to do this would be to change TaxonomyAdmin::managed_models to only manage TaxonomyTerm and not TaxonomyType

Going with that, would it be right to just update your existing PR to see if TaxonomyType::managed_models contains TaxonomyType?  And add a note to the readme about how to disable TaxonomyType's by updating the config for TaxonomyAdmin?

Or do you have a different solution in mind?

If you're happy to create a PR for this I'll get it merged for you.

**Comment by clarkepaul** [comment]
My thoughts... I think it depends on whether users can add types themselves or not. If they can add types, then plain text with something like "No types available" should be displayed. If the Tab for adding **Types** is removed then hiding the **Types** select dropdown completely makes sense (if I understand the UI correctly from comments above).

**Pull request closed without merging**
